layout_spectrum: 0.987484474433586
typography_spectrum: 0.3786359871737659
color:
  brandStrength: 0.9992761572357267
  lightness: 0.8985997810959816
  saturation: 0.8541872987989336
  rhythmicContrast: 0.23904260760173202
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
name: The Blog
